version : '3'

services:
  custom_alpine:
    image: alpine
    restart : always
    container_name: custom_alpine
    entrypoint: tail -f /dev/null
  
  custom_postgres:
    image: postgres:latest
    restart: always
    container_name: custom_postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
  
  custom_nginx:
    image: nginx
    restart: always
    container_name: custom_nginx
    ports:
      - "80:80"
    volumes:
      - ./mysite.template:/etc/nginx/conf.d/mysite.template
    environment:
      - NGINX_HOST=sample.com
      - NGINX_port=80
    links:
      - custom_postgres
      - custom_alpine

volumes:
  db-data:
    #external: true #Useful to use a pre-existing volume, but not useful right now.